### ISSUE TITLE
"AudioDeviceID doesn't exist" error on setting inputs

### ISSUE THREAD

**Issue by KingMob** [hladik-dan/switch-audio#2]
I'm on Ventura 13.0.1. Listing and setting output seems ok, but with _input_, I'm seeing errors like:

```shell
❯ switch-audio --list-input
[{"id":115,"name":"R-Phonak hearing aid","type":"input","isDefault":false},{"id":104,"name":"MacBook Pro Microphone","type":"input","isDefault":true}]

~ 
❯ switch-audio --set-input=115
The AudioDeviceID doesn't exist!

~ 
❯ switch-audio --set-input=104
The AudioDeviceID doesn't exist!
```

**Comment by hladik-dan** [comment]
Hello, thanks for the info. Should be fixed now. Please let me know if it works for you.

**Comment by KingMob** [comment]
It works! Thanks for this little tool.

In case you're curious, I use it because my hearing aids can act as both input and output. When I connect them to my laptop, macOS automatically sets them to both.

Unfortunately, hearing aid mics are (deliberately?) not designed for picking up your OWN voice, so I almost never want to use them over the built-in mic for input. So I've been messing with Shortcuts and Shortery to cobble together something that undoes it. I _was_ using Applescript to script System Settings, but that all broke with Ventura, and I couldn't find a good debugger.
